export const PATH = {
  login: '/logowanie',
  register: '/rejestracja',
  restorePassword: '/przypomnij-haslo',
  changePassword: `/zmiana-hasla/:token`,
  employment: '/pracownicy',
  documentWorkshop: '/wnioski/wnioski-szkoleniowe',
  documentAdditional: '/wnioski/wnioski-dodatkowe',
  workshopStudy: '/szkolenia/studia',
  workshopTraining: '/szkolenia/kursy',
  workshopOthers: '/szkolenia/inne',
  organizators: '/szkolenia/organizatorzy',
  workshopsCoaches: '/szkolenia/szkoleniowcy',
  workshopsInternalRoom: '/szkolenia-wewnetrzne/sale',
  workshopsInternalGroups: '/szkolenia-wewnetrzne/grupy',
  workshopsInternalMeeting: '/szkolenia-wewnetrzne/harmonogram',
  polls: '/ankiety',
  companyData: '/firma/dane-firmy',
  companyDataDepartments: '/firma/piony-wydzialy',
  companyDataPositions: '/firma/stanowiska',
  userAccount: '/moje-konto',
};
